### ISSUE TITLE
Would you be open to donating this name to the `purescript-web` organisation?

### ISSUE THREAD

**Issue by garyb** [ianbollinger/purescript-web-storage#3]
As per title. :smile:

Didn't realise this was a used name until earlier today when I tried to link against a branch I have in the https://github.com/purescript-web/purescript-web-storage repo!

I'm happy to add you as a maintainer or anything like that, but it would be great if we could get all these libraries under an organisation that can keep them maintained even if individual maintainers have no time or interest in doing so anymore. 🙂

**Comment by ianbollinger** [comment]
Absolutely, I haven't kept this package up to date and I don't want to be squatting on a valuable name. Do I need to do anything other than use `bower unregister`, i.e., regarding Pursuit?

**Comment by garyb** [comment]
I've invited you to the `purescript-web` organisation, I think that should give you permission to transfer the repository there - no need to unregister or anything, github will put redirects in place so that everything continues to work out.

Thanks!

**Comment by garyb** [comment]
Bump 🙂

**Comment by garyb** [comment]
Thanks very much!
